name: Extract Package JSON

on:
  schedule:
    - cron: '0 20 * * *' # Run daily at 20:00 UTC
  workflow_dispatch:

jobs:
  extract-monthly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Delete old processed files
        run: rm -rf processed/monthly

      - name: Run extract-monthly script
        run: uv run python extract_monthly_package_json.py

      - name: Commit monthly changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add processed/monthly
          # Only commit and push if there are staged changes
          if ! git diff --cached --quiet processed/monthly; then
            git commit -m "Update monthly package stats JSON"
            git pull --rebase
            git push
          else
            echo "No changes to commit."
          fi

  update-total:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run update-total script
        run: uv run python update_total_package_json.py

      - name: Commit total changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add processed/total
          if ! git diff --cached --quiet processed/total; then
            git commit -m "Update total package stats JSON"
            git pull --rebase
            git push
          else
            echo "No changes to commit."
          fi
